######################################################################
# Automatically generated by qmake (3.0) Wed Oct 11 09:08:38 2017
######################################################################

TEMPLATE = app
TARGET = example
INCLUDEPATH += .
QT += qml

# Input
SOURCES += main.cpp
RESOURCES += example.qrc

DESTDIR =  bin

isEmpty(PREFIX) {
  PREFIX = /usr/local
}


unix {
    target.path = $$PREFIX/$$DESTDIR
    INSTALLS += target
}
